### ISSUE TITLE
Error displaying contact when adding tag 

### ISSUE THREAD

**Issue by ruiming97** [AY2425S1-CS2103T-T14-2/tp#130]
<img width="1488" alt="image" src="https://github.com/user-attachments/assets/0341baac-2d69-41d3-85c3-ffe9ac4a7e81">
W

There is an error displaying the contact as shown in the image. Besides, the message could be more specific by adding what tag(s) is/are added.

**Comment by JiaYi-Gallium369** [comment]
## Add on
### Expected output message
`Added Tags to Contact: Alex Yang; Student ID: A1234567D; Phone: 234; Email: alexyeoh@example.com; Address: 22; Tags: [hiii] [hii]
### Actual output message
`Added Tags to Person: seedu.address.model.person.student.Student{name=Alex Yang, student id=A1234567D, phone=234, email=alexyeoh@example.com, address=22, tags=[[hiii], [hiiiii], [test], [hii]], attendance=0}`
