### ISSUE TITLE
[PE-D][Tester E] UG: Deletetag: The User Guide does not say that deletetag command is case sensetive.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-2/tp#217]
The deletetag command is case sensitive but no specification given in User Guide. Inconsistent case sensitivity between deletetag and tag. May confuse users as adding tags is case sensitive but deleting tags is not. 

![Screenshot 2024-11-08 164234.png](https://raw.githubusercontent.com/zlch/ped/main/files/4059d686-4943-4c40-b9d6-cbe712ffd0bb.png)

deletetag no information on case sensitivity. 

![Screenshot 2024-11-08 164322.png](https://raw.githubusercontent.com/zlch/ped/main/files/762f0e78-f1d5-447e-a73b-942ccad4f4fb.png)

tag is case-insensitive.

![Screenshot 2024-11-08 164337.png](https://raw.githubusercontent.com/zlch/ped/main/files/5a053ec5-6d42-46bf-b3f5-89d7c118e673.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: zlch/ped#7

**Comment by ruiming97** [comment]
Can be fixed

**Comment by leroychiu20** [comment]
> Can be fixed

i just update the ug to say deletetag is case-sensitive right. bcos otherwise will be enhancement already

**Comment by ruiming97** [comment]
> > Can be fixed
> 
> 
> 
> i just update the ug to say deletetag is case-sensitive right. bcos otherwise will be enhancement already

Ya ya
