### ISSUE TITLE
[PE-D][Tester D] Unhandled Check for Duplicate Phone Numbers 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-2/tp#226]
I feel like adding a student or company should check if they have duplicate phone numbers. :)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vinc3leong/ped#9

**Comment by leroychiu20** [comment]
good point, though not sure if this is a bug or enhancement. i think its more of an enhancement..?

**Comment by ruiming97** [comment]
Yup i added this in enhancement!

**Comment by JiaYi-Gallium369** [comment]
Fixed in #297
