### ISSUE TITLE
[PE-D][Tester D] Bugs with DG 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-2/tp#246]
Certain chunks of sections are duplicated in the DG. 

pg1 -11 are the same as pg 19 - 27 
pg 13 - 18 are the same as pg 33 - 39
pg 39 - 40 are the same as pg 44 - 45

-------------
Labels: `severity.High` `type.DocumentationBug`
original: vinc3leong/ped#13

**Comment by leroychiu20** [comment]
Rightly pointed out, something we noticed too on friday
