### ISSUE TITLE
[PE-D][Tester E] Student command: When adding student limitation that first letter of student ID has to be capitalized A and the last letter has to be capitalized is not given in the program as well as User Guide.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-2/tp#250]
![Screenshot 2024-11-08 174826.png](https://raw.githubusercontent.com/zlch/ped/main/files/e0cf5625-af85-4932-86e9-dc2e5f7ceb7e.png)

![Screenshot 2024-11-08 174840.png](https://raw.githubusercontent.com/zlch/ped/main/files/032f569f-b60e-40a8-94cf-db9c55bd7c90.png)

![Screenshot 2024-11-08 175328.png](https://raw.githubusercontent.com/zlch/ped/main/files/29a271dc-f1b9-460f-8974-adfa1fb23d02.png)

This could confuse users as they may not know how to correct the issue they are facing when the error message is given.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zlch/ped#13

**Comment by ruiming97** [comment]
Update user guide
