### ISSUE TITLE
[PE-D][Tester E] DG: UC05: Use case resumes from incorrect step.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-2/tp#257]
The use case resumes from step 1 for the extensions but it should resume from step 2 as it is not neccasary to request the list again on invalid input.

![Screenshot 2024-11-08 203045.png](https://raw.githubusercontent.com/zlch/ped/main/files/867c9932-dd03-4b90-804d-0baff7a8203c.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: zlch/ped#19

**Comment by ruiming97** [comment]
Can be fixed
