### ISSUE TITLE
[PE-D][Tester E] UG: Glossary missing some terms that may be useful to users.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-2/tp#259]
While the meaning of 'relative path' and 'absolute path' are given. The definition of a path itself is not explained which may confuse users as the path mentioned differs from the layman use of path. Providing the meaning of 'directory' may also be useful for user.
![Screenshot 2024-11-08 203744.png](https://raw.githubusercontent.com/zlch/ped/main/files/e9ce1908-00d4-4b80-9f2d-7a9763072f52.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: zlch/ped#21

**Comment by ruiming97** [comment]
Ya i think path should be added in as well
